### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by tjluoma** [grahampugh/macadmin-scripts#19]
`PublicSeed` seems to work OK but `CustomerSeed` and `DeveloperSeed` are giving me errors.

ISTR that this was working just a day or two ago (maybe yesterday) so I am wondering if perhaps Apple changed something.

---------------------------------------------------------------------------------------------------------------------------
## CustomerSeed

```
sudo installinstallmacos.py  --seedprogram CustomerSeed

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : MacBookPro16,1
Board ID         : Mac-E1008331FDC96864
OS Version       : 10.15.6
Build ID         : 19G73

No server metadata for 001-26097
 #  ProductID       Version    Build    Post Date   Title                          Notes
 1  061-77704       10.15.4    19E242d  2020-02-26  macOS Catalina Beta            Unsupported macOS version
 2  001-15219       10.15.5    19F2200  2020-06-15  macOS Catalina                 Unsupported Board ID
 3  001-06847       10.15.6    19G60d   2020-06-30  macOS Catalina Beta
 4  001-04366       10.15.4    19E2269  2020-05-04  macOS Catalina                 Unsupported Board ID
 5  061-86291       10.15.3    19D2064  2020-03-23  macOS Catalina                 Unsupported Board ID
 6  041-91758       10.13.6    17G66    2019-10-19  macOS High Sierra              Unsupported Board ID
 7  041-88800       10.14.4    18E2034  2019-10-23  macOS Mojave                   Unsupported Board ID
 8  061-26589       10.14.6    18G103   2019-10-14  macOS Mojave                   Unsupported Board ID
 9  061-94403       10.15.6    19G73    2020-07-15  macOS Catalina
Traceback (most recent call last):
  File "/usr/local/scripts/installinstallmacos.py", line 1125, in <module>
    main()
  File "/usr/local/scripts/installinstallmacos.py", line 809, in main
    if hw_model in product_info[product_id]["UnsupportedModels"] and is_vm == False:
TypeError: argument of type 'NoneType' is not iterable
```

-----------------------------------------------------------------------------------------------------------------------------

## DeveloperSeed

-----------------------------------------------------------------------------------------------------------------------------

```
sudo installinstallmacos.py  --seedprogram DeveloperSeed

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : MacBookPro16,1
Board ID         : Mac-E1008331FDC96864
OS Version       : 10.15.6
Build ID         : 19G73

No server metadata for 001-26097
 #  ProductID       Version    Build    Post Date   Title                          Notes
 1  061-77704       10.15.4    19E242d  2020-02-26  macOS Catalina Beta            Unsupported macOS version
 2  001-15219       10.15.5    19F2200  2020-06-15  macOS Catalina                 Unsupported Board ID
 3  001-04366       10.15.4    19E2269  2020-05-04  macOS Catalina                 Unsupported Board ID
 4  061-86291       10.15.3    19D2064  2020-03-23  macOS Catalina                 Unsupported Board ID
 5  041-91758       10.13.6    17G66    2019-10-19  macOS High Sierra              Unsupported Board ID
 6  041-88800       10.14.4    18E2034  2019-10-23  macOS Mojave                   Unsupported Board ID
 7  061-26589       10.14.6    18G103   2019-10-14  macOS Mojave                   Unsupported Board ID
 8  061-94403       10.15.6    19G73    2020-07-15  macOS Catalina
Traceback (most recent call last):
  File "/usr/local/scripts/installinstallmacos.py", line 1125, in <module>
    main()
  File "/usr/local/scripts/installinstallmacos.py", line 809, in main
    if hw_model in product_info[product_id]["UnsupportedModels"] and is_vm == False:
TypeError: argument of type 'NoneType' is not iterable
```

------------------------------------------------------------------------------------------------------------------------------------

**Comment by grahampugh** [comment]
@tjluoma I have now addressed this, up to a point. 

The Big Sur beta (ProductID 001-26097) contains no data for supported Build IDs or unsupported models, so the script was spitting out an error when trying to use this information to calculate which builds are valid for the system on which the script is running. 

I've now added checks to see if these data are populated in the catalog entries, and if not it will show a warning.
